@Library('jenkins-shared-libraries@feature-cicd') _

def targetEnv  = (params.ENVIRONMENT ?: 'TEST').toUpperCase()
def imageTag   = params.image_tag ?: 'latest'
def currentEnv = inventory.cd('HRC-AMD-Sync-Service', targetEnv)

node('HRC-Kollect-Jenkins-Agent') {
    currentBuild.description = "CD: HRC-AMD-Sync-Service | Env: ${targetEnv} | Tag: ${imageTag}"


    def cdPipeline = new opstree.cd.templates.docker_ecr.docker_deployment()
    cdPipeline.call([
        enable_jenkins_build_param_override     : true,

        // WORKSPACE MANAGEMENT
        clean_workspace                         : true,

        // APPLICATION / CONTAINER NAME
        app_name                                : currentEnv.app_name,

        // TARGET SERVER
        server_ip                               : currentEnv.server_ip,
        ssh_credentials_id                      : currentEnv.ssh_creds,

        // ECR
        ecr_account                             : currentEnv.ecr_account,
        ecr_region                              : currentEnv.ecr_region,
        ecr_repo                                : currentEnv.ecr_repo,

        // PORTS
        container_port                          : currentEnv.container_port,
        host_port                               : currentEnv.host_port,

        // NOTIFICATIONS
        notification_enabled                    : true,
        notification_channel                    : 'gmail',
        gmail_notification_from_email_id        : 'smtp@kernernorland.com',
        gmail_notification_recipients_email_ids : 'asangai@healthreconconnect.com'
    ])
}
