@Library('jenkins-shared-libraries@feature-cicd') _

def targetEnv = (params.ENVIRONMENT ?: 'TEST').toUpperCase()
def imageTag = params.image_tag ?: 'latest'

def envMap = [
    'TEST': [server_ip: '10.2.30.254', ssh_creds: 'HRC-Kollect-Test-Server', app_name: 'hrc-amd-sync-service-test', ecr_repo: 'hrc-kollect-cicd/apps'],
    'DEV' : [server_ip: '10.2.40.133', ssh_creds: 'HRC-Kollect-Dev-Server',  app_name: 'hrc-amd-sync-service-dev',  ecr_repo: 'hrc-amd-sync-service-dev'],
    'QA'  : [server_ip: '10.2.10.111', ssh_creds: 'HRC-Kollect-QA-Server',   app_name: 'hrc-amd-sync-service-qa',   ecr_repo: 'hrc-amd-sync-service-qa'],
    'DEMO': [server_ip: '10.2.40.238', ssh_creds: 'HRC-Kollect-Demo-Server', app_name: 'hrc-amd-sync-service-demo', ecr_repo: 'hrc-amd-sync-service-demo'],
    'STG' : [server_ip: '10.2.40.170', ssh_creds: 'HRC-Kollect-Stg-Server',  app_name: 'hrc-amd-sync-service-stg',  ecr_repo: 'hrc-amd-sync-service-stg'],
    'PROD': [server_ip: '10.2.10.118', ssh_creds: 'HRC-Kollect-PROD-Server', app_name: 'hrc-amd-sync-service-prod', ecr_repo: 'hrc-amd-sync-service-prod']
]

def currentEnv = envMap[targetEnv] ?: envMap['TEST']

node('HRC-Kollect-Jenkins-Agent') {
    currentBuild.description = "CD: HRC-AMD-Sync-Service | Env: ${targetEnv} | Tag: ${imageTag}"

    def cdPipeline = new opstree.cd.templates.docker_ecr.docker_deployment()
    cdPipeline.call([
        enable_jenkins_build_param_override: true,

        // WORKSPACE MANAGEMENT
        clean_workspace                     : true,

        // APPLICATION / CONTAINER NAME
        app_name                            : currentEnv.app_name,
        
        // TARGET SERVER
        server_ip                           : currentEnv.server_ip,
        ssh_credentials_id                  : currentEnv.ssh_creds,

        // ECR
        ecr_account                         : '167121004129',
        ecr_region                          : 'us-east-1',
        ecr_repo                            : currentEnv.ecr_repo,

        // PORTS
        container_port                      : 8180,
        host_port                           : 8080,

        // NOTIFICATIONS
        notification_enabled                    : true,
        notification_channel                    : 'gmail',
        gmail_notification_from_email_id        : 'smtp@kernernorland.com',
        gmail_notification_recipients_email_ids : 'asangai@healthreconconnect.com'
    ])
}
