@Library('jenkins-shared-libraries@feature-cicd') _
def cdpipeline = new opstree.cd.templates.s3_fe.s3_deployment()

def targetEnv  = (params.ENVIRONMENT ?: 'DEV').toUpperCase()
def currentEnv = inventory.cd('Non-Healthcare-FE', targetEnv)

node('HRC-Kollect-Jenkins-Agent') {
    cdpipeline.call([
        enable_jenkins_build_param_override: true,

        // WORKSPACE MANAGEMENT
        clean_workspace      : true,

        // VCS MANAGEMENT
        repo_https_url       : 'https://gitlab.healthreconconnect.com/hrc/one-kollect-frontend.git',
        repo_url_type        : 'http',
        jenkins_git_creds_id : 'hasantha-hrc-gitlab-access',

        // S3 & CLOUDFRONT DEPLOYMENT (DYNAMIC BY ENVIRONMENT)
        s3_bucket            : currentEnv.s3_bucket,
        cloudfront_dist_id   : currentEnv.cloudfront_id,
        node_version         : 'Node-14',
        build_command        : 'yarn build',

        // NOTIFICATION
        notification_enabled                    : true,
        notification_channel                    : 'gmail',
        gmail_notification_from_email_id        : 'smtp@kernernorland.com',
        gmail_notification_recipients_email_ids : 'asangai@healthreconconnect.com'
    ])
}
