@Library('jenkins-shared-libraries@feature-cicd') _
def cdpipeline = new opstree.cd.templates.ssh_pm2.ssh_pm2_deployment()

def targetEnv    = (params.ENVIRONMENT ?: env.ENVIRONMENT ?: 'TEST').trim().toUpperCase()
def artifactName = (env.artifact_name ?: params.artifact_name ?: env.image_tag ?: params.image_tag ?: 'latest').trim()

def currentEnv = inventory.cd('HRC-Kollect-Client-Billing-FE', targetEnv)
def ciEnv      = inventory.ci('HRC-Kollect-Client-Billing-FE', targetEnv)

node('HRC-Kollect-Jenkins-Agent') {
    currentBuild.description = "CD: HRC-Kollect-Client-Billing-FE | Env: ${targetEnv} | Artifact: ${artifactName}"

    cdpipeline.call([
        enable_jenkins_build_param_override: true,

        // WORKSPACE MANAGEMENT
        clean_workspace                 : true,

        // ENVIRONMENT & BRANCH
        ENVIRONMENT                     : targetEnv,
        BRANCH                          : params.BRANCH ?: 'main',

        // ARTIFACT CONFIGURATION (S3)
        artifact_s3_bucket_name         : ciEnv.artifact_s3_bucket_name,
        artifact_s3_bucket_aws_region   : ciEnv.aws_region,
        artifact_s3_keypath_destination : ciEnv.artifact_s3_keypath,
        artifact_name                   : artifactName,
        jenkins_aws_credentials_id      : ciEnv.credentials_id,

        // TARGET VM & ENVIRONMENT BINDINGS
        server_ip                       : currentEnv.server_ip,
        deploy_dir                      : currentEnv.deploy_dir,
        app_name                        : currentEnv.app_name,
        node_version                    : 'v24.6.0',
        ssh_credentials_id              : currentEnv.ssh_creds,

        // FRONTEND RUNTIME CONFIGURATION (.env)
        custom_env_content              : """
NEXT_PUBLIC_CDN_URL=https://d2a99t4hv2ijwl.cloudfront.net
NEXT_PUBLIC_K1_BASE_URL=${currentEnv.k1_url}
NODE_ENV=production
PORT=3100
""".stripIndent(),

        // STARTUP & HEALTH CHECK
        start_command                   : 'npm run start',
        health_check_endpoint           : 'http://127.0.0.1:3100/',

        // NOTIFICATIONS
        notification_enabled                    : true,
        notification_channel                    : 'gmail',
        gmail_notification_from_email_id        : 'smtp@kernernorland.com',
        gmail_notification_recipients_email_ids : 'asangai@healthreconconnect.com'
    ])
}