@Library('jenkins-shared-libraries@feature-cicd') _
def cdpipeline = new opstree.cd.templates.s3_fe.s3_deployment()

def targetEnv = (params.ENVIRONMENT ?: 'DEV').toUpperCase()

def envMap = [
    'DEV' : [s3_bucket: 'hrckollect-dev-fe', cloudfront_id: 'E1RYWTTS4NPREW'],
    'QA'  : [s3_bucket: 'hrckollect-qa-fe', cloudfront_id: 'E1RYWTTS4NPREW'],
    'DEMO': [s3_bucket: 'hrckollect-demo-fe', cloudfront_id: 'E1RYWTTS4NPREW'],
    'STG' : [s3_bucket: 'hrckollect-stg-fe', cloudfront_id: 'E1RYWTTS4NPREW'],
    'PROD': [s3_bucket: 'hrckollect-prod-fe', cloudfront_id: 'E1RYWTTS4NPREW']
]

def currentEnv = envMap[targetEnv] ?: envMap['DEV']

node('HRC-Kollect-Jenkins-Agent') {
    cdpipeline.call([
        enable_jenkins_build_param_override: true,

        // WORKSPACE MANAGEMENT
        clean_workspace      : true,

        // S3 & CLOUDFRONT DEPLOYMENT (DYNAMIC BY ENVIRONMENT)
        s3_bucket            : currentEnv.s3_bucket,
        cloudfront_dist_id   : currentEnv.cloudfront_id,
        aws_region           : 'us-east-1',
        artifact_source_path : 'dist/',

        // NOTIFICATION
        notification_enabled                    : true,
        notification_channel                    : 'gmail',
        gmail_notification_from_email_id        : 'smtp@kernernorland.com',
        gmail_notification_recipients_email_ids : 'asangai@healthreconconnect.com'
    ])
}
