@Library('jenkins-shared-libraries@feature-cicd') _
def cipipeline = new opstree.ci.templates.nodejs_ci.nodejs_ci()

def targetEnv = (params.ENVIRONMENT ?: 'TEST').toUpperCase()

def envMap = [
    'TEST': [artifact_s3_bucket_name: 'hrc-cicd-test-bucket', artifact_s3_keypath: 'HRC-Kollect-Pay-Portal-BE', aws_region: 'us-east-1', credentials_id: 'hrc-aws-ecr-credentials'],
    'DEV' : [artifact_s3_bucket_name: 'hrc-cicd-test-bucket', artifact_s3_keypath: 'HRC-Kollect-Pay-Portal-BE', aws_region: 'us-east-1', credentials_id: 'hrc-aws-ecr-credentials'],
    'QA'  : [artifact_s3_bucket_name: 'hrc-cicd-test-bucket', artifact_s3_keypath: 'HRC-Kollect-Pay-Portal-BE', aws_region: 'us-east-1', credentials_id: 'hrc-aws-ecr-credentials'],
    'DEMO': [artifact_s3_bucket_name: 'hrc-cicd-test-bucket', artifact_s3_keypath: 'HRC-Kollect-Pay-Portal-BE', aws_region: 'us-east-1', credentials_id: 'hrc-aws-ecr-credentials'],
    'STG' : [artifact_s3_bucket_name: 'hrc-cicd-test-bucket', artifact_s3_keypath: 'HRC-Kollect-Pay-Portal-BE', aws_region: 'us-east-1', credentials_id: 'hrc-aws-ecr-credentials'],
    'PROD': [artifact_s3_bucket_name: 'hrc-cicd-test-bucket', artifact_s3_keypath: 'HRC-Kollect-Pay-Portal-BE', aws_region: 'us-east-1', credentials_id: 'hrc-aws-ecr-credentials']
]

def currentEnv = envMap[targetEnv] ?: envMap['TEST']

node('HRC-Kollect-Jenkins-Agent') {
    cipipeline.call([
        enable_jenkins_build_param_override: true,

        // WORKSPACE MANAGEMENT
        clean_workspace                   : true,

        // VCS MANAGEMENT
        repo_https_url                    : 'https://gitlab.healthreconconnect.com/hrc/kollect-payportal-be.git',
        repo_ssh_url                      : 'git@gitlab.healthreconconnect.com:hrc/kollect-payportal-be.git',
        repo_branch                       : params.BRANCH ?: 'main',
        repo_url_type                     : 'http',
        jenkins_git_creds_id              : 'piyushu-gitlab-token',
        source_code_path                  : '',

        // PRE-BUILD CHECKS
        gitleaks_check                    : true,
        fail_job_if_leak_detected         : false,
        gitleaks_scan_mode                : 'full',
        gitleaks_report_jenkins_publish   : true,

        dependency_check                  : 'false',
        unit_testing_check                : 'false',
        static_code_analysis_check        : false,

        // BUILD & PACKAGE ARTIFACT
        perform_code_build                : true,
        node_version                      : '20',
        package_manager                   : 'yarn',
        app_name                          : 'hrc-kollect-pay-portal-be',
        build_command                     : 'yarn build',
        build_output_path                 : 'dist',
        include_node_modules              : true,
        prune_dev_dependencies            : true,
        additional_artifact_paths         : [
            'package.json',
            'yarn.lock'
        ],

        // PUBLISH TO S3
        artifact_publish_check            : true,
        artifact_destination_type         : 'S3',
        jenkins_aws_credentials_id        : currentEnv.credentials_id,
        artifact_s3_bucket_aws_region     : currentEnv.aws_region,
        artifact_s3_bucket_name           : currentEnv.artifact_s3_bucket_name,
        artifact_s3_keypath_destination   : currentEnv.artifact_s3_keypath,

        // TRIGGER CD PIPELINE
        enable_trigger_cd_pipeline        : params.TRIGGER_CD != null ? params.TRIGGER_CD : true,
        trigger_cd_pipeline_path          : 'CD/HRC-Kollect-Pay-Portal-BE',
        image_tag_build_param             : 'artifact_name',
        environment                       : targetEnv,

        // NOTIFICATION
        notification_enabled                    : true,
        notification_channel                    : 'gmail',
        gmail_notification_from_email_id        : 'smtp@kernernorland.com',
        gmail_notification_recipients_email_ids : 'asangai@healthreconconnect.com'
    ])
}