// @Library('jenkins-shared-libraries@feature-cicd') _
// def cipipeline = new opstree.ci.templates.java_ci.java_ci()

// def ciEnvConfig = [
//     DEV : [account_id: '167121004129', ecr_region: 'us-east-1', ecr_repo_name: 'kollect-reporting-module-dev'],
//     DEMO: [account_id: '167121004129', ecr_region: 'us-east-1', ecr_repo_name: 'kollect-reporting-module-demo'],
//     QA  : [account_id: '167121004129', ecr_region: 'us-east-1', ecr_repo_name: 'kollect-reporting-module-qa'],
//     STG : [account_id: '167121004129', ecr_region: 'us-east-1', ecr_repo_name: 'kollect-reporting-module-stg'],
//     PROD: [account_id: '167121004129', ecr_region: 'us-east-1', ecr_repo_name: 'kollect-reporting-module-prod']
// ]

// node('HRC-Kollect-Jenkins-Agent') {
//     def targetEnv = (params.ENVIRONMENT ?: 'DEV').toUpperCase()
//     def env_cfg = ciEnvConfig[targetEnv] ?: ciEnvConfig['DEV']

//     cipipeline.call([
//         enable_jenkins_build_param_override: true,

//         // WORKSPACE MANAGEMENT
//         clean_workspace                  : true,

//         // VCS MANAGEMENT
//         repo_https_url                   : 'https://gitlab.healthreconconnect.com/hrc/kollect-report-service.git',
//         repo_ssh_url                     : 'git@gitlab.healthreconconnect.com:hrc/kollect-report-service.git',
//         repo_branch                      : params.BRANCH ?: 'main',
//         repo_url_type                    : 'http',
//         jenkins_git_creds_id             : 'hasantha-hrc-gitlab-access',
//         source_code_path                 : '',

//         // PRE-BUILD CHECKS
//         // CREDS SCANNING (GITLEAKS)
//         gitleaks_check                   : true,
//         fail_job_if_leak_detected        : false,
//         gitleaks_scan_mode               : 'full',
//         gitleaks_report_jenkins_publish  : true,

//         // DEPENDENCY SCANNING (OWASP)
//         dependency_check                          : 'false',
//         dependency_scan_tool                      : 'owasp',
//         owasp_project_name                        : 'kollect-reporting-module',
//         owasp_report_publish                      : 'true',
//         owasp_report_format                       : 'html',
//         fail_job_if_dependency_returned_exception : 'false',
//         nvd_api_key_creds_id                      : 'NVD_API_KEY',

//         // BUILD ARTIFACT (Java / Maven)
//         perform_code_build               : true,
//         build_tool                       : 'maven',
//         java_version                     : '17',
//         pom_location                     : 'pom.xml',

//         // UNIT TESTING
//         unit_testing_check               : 'false',
//         fail_job_if_unit_issue_detected  : 'false',
//         unit_test_reports_path           : '**/target/surefire-reports/*.xml',

//         // STATIC CODE ANALYSIS (SONARQUBE)
//         static_code_analysis_check              : false,
//         codebase_to_scan_directory              : '.',
//         sonar_project_key                       : 'kollect-reporting-module',
//         sonar_project_name                      : 'kollect-reporting-module',
//         sonar_sources                           : 'src/main/java',
//         fail_job_if_analysis_returned_exception : 'false',
//         jenkins_sonarqube_token_creds_id        : 'HRC_SONARQUBE_TOKEN',

//         // DOCKER BUILD
//         perform_build_dockerfile         : true,
//         image_name                       : 'kollect-reporting-module',
//         image_tag                        : "${currentBuild.number}",
//         dockerfile_location              : 'Dockerfile',

//         // POST-BUILD CHECKS
//         // IMAGE SCANNING (TRIVY)
//         image_scanning_check             : true,
//         scan_severity                    : 'HIGH,CRITICAL',
//         image_scanning_report_publish    : 'true',

//         // IMAGE SIZE VALIDATOR
//         image_size_validator_check       : true,
//         max_allowed_image_size           : '1000',
//         fail_job_if_validation_fail      : 'false',

//         // PUBLISH ARTIFACT (ECR)
//         artifact_publish_check           : true,
//         artifact_destination_type        : 'ecr',
//         docker_image_name                : 'kollect-reporting-module',
//         jenkins_aws_credentials_id       : 'HRC_AWS_CREDENTIALS',
//         ecr_repo_name                    : env_cfg.ecr_repo_name,
//         ecr_region                       : env_cfg.ecr_region,
//         account_id                       : env_cfg.account_id,

//         // TRIGGER CD PIPELINE
//         enable_trigger_cd_pipeline       : params.TRIGGER_CD != null ? params.TRIGGER_CD : true,
//         trigger_cd_pipeline_path         : 'CD/HRC-Kollect-Reporting-Module',
//         image_tag_build_param            : 'image_tag',

//         // NOTIFICATION
//         notification_enabled                    : true,
//         notification_channel                    : 'gmail',
//         gmail_notification_from_email_id        : 'smtp@kernernorland.com',
//         gmail_notification_recipients_email_ids : 'asangai@healthreconconnect.com'
//     ])
// }
//-----------------


@Library('jenkins-shared-libraries@feature-cicd') _
def cipipeline = new opstree.ci.templates.java_ci.java_ci()

def ciEnvConfig = [
    DEV : [account_id: '167121004129', ecr_region: 'us-east-1', ecr_repo_name: 'kollect-reporting-module-dev'],
    DEMO: [account_id: '167121004129', ecr_region: 'us-east-1', ecr_repo_name: 'kollect-reporting-module-demo'],
    QA  : [account_id: '167121004129', ecr_region: 'us-east-1', ecr_repo_name: 'kollect-reporting-module-qa'],
    STG : [account_id: '167121004129', ecr_region: 'us-east-1', ecr_repo_name: 'kollect-reporting-module-stg'],
    PROD: [account_id: '167121004129', ecr_region: 'us-east-1', ecr_repo_name: 'kollect-reporting-module-prod']
]

node('HRC-Kollect-Jenkins-Agent') {
    def targetEnv = (params.ENVIRONMENT ?: 'DEV').toUpperCase()
    def env_cfg = ciEnvConfig[targetEnv] ?: ciEnvConfig['DEV']

    cipipeline.call([
        enable_jenkins_build_param_override: true,

        // WORKSPACE MANAGEMENT
        clean_workspace                  : true,

        // VCS MANAGEMENT
        repo_https_url                   : 'https://gitlab.healthreconconnect.com/hrc/kollect-report-service.git',
        repo_ssh_url                     : 'git@gitlab.healthreconconnect.com:hrc/kollect-report-service.git',
        repo_branch                      : params.BRANCH ?: 'main',
        repo_url_type                    : 'http',
        jenkins_git_creds_id             : 'piyushu-gitlab-token',
        source_code_path                 : '',

        // PRE-BUILD CHECKS
        // CREDS SCANNING (GITLEAKS)
        gitleaks_check                   : true,
        fail_job_if_leak_detected        : false,
        gitleaks_scan_mode               : 'full',
        gitleaks_report_jenkins_publish  : true,

        // DEPENDENCY SCANNING (OWASP)
        dependency_check                          : 'false',
        dependency_scan_tool                      : 'owasp',
        owasp_project_name                        : 'kollect-reporting-module',
        owasp_report_publish                      : 'true',
        owasp_report_format                       : 'html',
        fail_job_if_dependency_returned_exception : 'false',
        nvd_api_key_creds_id                      : 'NVD_API_KEY',

        // BUILD ARTIFACT (Java / Maven)
        perform_code_build               : true,
        build_tool                       : 'maven',
        java_version                     : '17',
        pom_location                     : '',
        codeartifact_dependency          : false,
        artifact_jar_name                : 'report-service-APP_VERSION.jar',

        // UNIT TESTING
        unit_testing_check               : 'false',
        fail_job_if_unit_issue_detected  : 'false',
        unit_test_reports_path           : '**/target/surefire-reports/*.xml',

        // STATIC CODE ANALYSIS (SONARQUBE)
        static_code_analysis_check              : false,
        codebase_to_scan_directory              : '.',
        sonar_project_key                       : 'kollect-reporting-module',
        sonar_project_name                      : 'kollect-reporting-module',
        sonar_sources                           : 'src/main/java',
        fail_job_if_analysis_returned_exception : 'false',
        jenkins_sonarqube_token_creds_id        : 'HRC_SONARQUBE_TOKEN',

        // DOCKER BUILD
        perform_build_dockerfile         : true,
        image_name                       : 'kollect-reporting-module',
        image_tag                        : "${currentBuild.number}",
        dockerfile_location              : 'Dockerfile',

        // POST-BUILD CHECKS
        // IMAGE SCANNING (TRIVY)
        image_scanning_check             : true,
        scan_severity                    : 'HIGH,CRITICAL',
        image_scanning_report_publish    : 'true',

        // IMAGE SIZE VALIDATOR
        image_size_validator_check       : true,
        max_allowed_image_size           : '1000',
        fail_job_if_validation_fail      : 'false',

        // PUBLISH ARTIFACT (ECR)
        artifact_publish_check           : true,
        artifact_destination_type        : 'ecr',
        docker_image_name                : 'kollect-reporting-module',
        jenkins_aws_credentials_id       : 'HRC_AWS_CREDENTIALS',
        ecr_repo_name                    : 'hrc-kollect-cicd/apps',
        ecr_region                       : env_cfg.ecr_region,
        account_id                       : env_cfg.account_id,

        // TRIGGER CD PIPELINE
        enable_trigger_cd_pipeline       : params.TRIGGER_CD != null ? params.TRIGGER_CD : true,
        trigger_cd_pipeline_path         : 'CD/HRC-Kollect-Reporting-Module',
        image_tag_build_param            : 'image_tag',

        // NOTIFICATION
        notification_enabled                    : true,
        notification_channel                    : 'gmail',
        gmail_notification_from_email_id        : 'smtp@kernernorland.com',
        gmail_notification_recipients_email_ids : 'asangai@healthreconconnect.com'
    ])
}
