@Library('jenkins-shared-libraries@feature-cicd') _
def cdpipeline = new opstree.cd.templates.s3_fe.s3_deployment()

def targetEnv  = (params.ENVIRONMENT ?: 'TEST').toUpperCase()
def currentEnv = inventory.cd('HRC-Kollect-FE', targetEnv)

node('HRC-Kollect-Jenkins-Agent') {
    cdpipeline.call([
        enable_jenkins_build_param_override: true,

        // WORKSPACE MANAGEMENT
        clean_workspace      : true,

        // S3 & CLOUDFRONT DEPLOYMENT (DYNAMIC BY ENVIRONMENT)
        s3_bucket            : currentEnv.s3_bucket,
        cloudfront_dist_id   : currentEnv.cloudfront_id,
        aws_region           : 'us-east-1',
        artifact_source_path : 'dist/',

        // NOTIFICATION
        notification_enabled                    : true,
        notification_channel                    : 'gmail',
        gmail_notification_from_email_id        : 'smtp@kernernorland.com',
        gmail_notification_recipients_email_ids : 'asangai@healthreconconnect.com'
    ])
}
