@Library('jenkins-shared-libraries@feature-cicd') _
def cdpipeline = new opstree.cd.templates.ssh_pm2.ssh_pm2_deployment()

def targetEnv  = (params.ENVIRONMENT ?: 'DEV').toUpperCase()
def currentEnv = inventory.cd('Non-Healthcare-BE', targetEnv)

node('HRC-Kollect-Jenkins-Agent') {
    cdpipeline.call([
        enable_jenkins_build_param_override: true,

        // WORKSPACE MANAGEMENT
        clean_workspace      : true,

        // ARTIFACT CONFIGURATION - MUST MATCH CI S3 LOCATION
        artifact_s3_bucket_name         : 'hrc-cicd-test-bucket',
        artifact_s3_bucket_aws_region   : 'us-east-1',
        artifact_s3_keypath_destination : 'Non-Healthcare-BE',
        artifact_name                   : params.artifact_name ?: '',

        // VCS MANAGEMENT
        repo_https_url       : 'https://gitlab.healthreconconnect.com/hrc/one-kollect-core-service.git',
        repo_branch          : params.BRANCH ?: 'main',
        repo_url_type        : 'http',
        jenkins_git_creds_id : 'piyushu-gitlab-token',
        source_code_path     : '',

        // DYNAMIC DEPLOYMENT CONFIG (BY ENVIRONMENT)
        server_ip            : currentEnv.server_ip,
        deploy_dir           : currentEnv.deploy_dir,
        app_name             : currentEnv.app_name,
        node_version         : 'v20.20.2',
        ssh_credentials_id   : currentEnv.ssh_creds,
        secret_arn           : currentEnv.secret_arn,
        package_manager      : 'yarn',
        start_command        : 'yarn start',
        health_check_endpoint : 'http://127.0.0.1:80/api/health',

        // NOTIFICATION
        notification_enabled                    : true,
        notification_channel                    : 'gmail',
        gmail_notification_from_email_id        : 'smtp@kernernorland.com',
        gmail_notification_recipients_email_ids : 'asangai@healthreconconnect.com'
    ])
}
