@Library('jenkins-shared-libraries@feature-cicd') _
def cdpipeline = new opstree.cd.templates.ssh_pm2.ssh_pm2_deployment()

def targetEnv = (params.ENVIRONMENT ?: 'DEV').toUpperCase()

def envMap = [
    'DEV' : [server_ip: '10.2.40.183', deploy_dir: '/opt/non-healthcare-dev/backend', app_name: 'non-healthcare-dev-backend', ssh_creds: 'Non-Healthcare-dev-server', secret_arn: 'arn:aws:secretsmanager:us-east-1:167121004129:secret:dev.nonhealthcare.com-kg1Ktx'],
    'QA'  : [server_ip: '10.2.40.239', deploy_dir: '/opt/non-healthcare-qa/backend', app_name: 'non-healthcare-qa-backend', ssh_creds: 'Non-Healthcare-qa-server', secret_arn: 'arn:aws:secretsmanager:us-east-1:167121004129:secret:qa.nonhealthcare.com-3xKQQa'],
    'DEMO': [server_ip: '10.2.40.110', deploy_dir: '/opt/non-healthcare-demo/backend', app_name: 'non-healthcare-demo-backend', ssh_creds: 'Non-Healthcare-demo-server', secret_arn: 'arn:aws:secretsmanager:us-east-1:167121004129:secret:demo.nonhealthcare.com-fpjxjz']
]

def currentEnv = envMap[targetEnv] ?: envMap['DEV']

node('HRC-Kollect-Jenkins-Agent') {
    cdpipeline.call([
        enable_jenkins_build_param_override: true,

        // WORKSPACE MANAGEMENT
        clean_workspace      : true,

        // VCS MANAGEMENT
        repo_https_url       : 'https://gitlab.healthreconconnect.com/hrc/one-kollect-core-service.git',
        repo_branch          : params.BRANCH ?: 'main',
        repo_url_type        : 'http',
        jenkins_git_creds_id : 'hasantha-hrc-gitlab-access',
        source_code_path     : '',

        // DYNAMIC DEPLOYMENT CONFIG (BY ENVIRONMENT)
        server_ip            : currentEnv.server_ip,
        deploy_dir           : currentEnv.deploy_dir,
        app_name             : currentEnv.app_name,
        node_version         : 'v16.17.0',
        ssh_credentials_id   : currentEnv.ssh_creds,
        secret_arn           : currentEnv.secret_arn,
        package_manager      : 'yarn',
        start_command        : 'yarn start',

        // NOTIFICATION
        notification_enabled                    : true,
        notification_channel                    : 'gmail',
        gmail_notification_from_email_id        : 'smtp@kernernorland.com',
        gmail_notification_recipients_email_ids : 'asangai@healthreconconnect.com'
    ])
}
