@Library('jenkins-shared-libraries@feature-cicd') _
def cdpipeline = new opstree.cd.templates.docker_ecr.docker_deployment()

def targetEnv  = (params.ENVIRONMENT ?: 'TEST').toUpperCase()
def imageTag   = params.image_tag ?: 'latest'
def currentEnv = inventory.cd('HRC-Kollect-Reporting-Module', targetEnv)

node('HRC-Kollect-Jenkins-Agent') {
    currentBuild.description = "CD: HRC-Kollect-Reporting-Module | Env: ${targetEnv} | Tag: ${imageTag}"

    cdpipeline.call([
        enable_jenkins_build_param_override: true,

        // WORKSPACE MANAGEMENT
        clean_workspace      : true,

        // DOCKER CONTAINER DEPLOYMENT (SSH -> Remote Server)
        server_ip            : currentEnv.server_ip,
        ssh_credentials_id   : currentEnv.ssh_creds,
        app_name             : currentEnv.app_name,
        ecr_repo             : 'hrc-kollect-cicd/apps',
        ecr_account          : '167121004129',
        ecr_region           : 'us-east-1',
        container_port       : '8080',
        host_port            : '8080',

        // NOTIFICATION
        notification_enabled                    : true,
        notification_channel                    : 'gmail',
        gmail_notification_from_email_id        : 'smtp@kernernorland.com',
        gmail_notification_recipients_email_ids : 'asangai@healthreconconnect.com'
    ])
}
