@Library('jenkins-shared-libraries@feature-cicd') _
def cdpipeline = new opstree.cd.templates.ssh_pm2.ssh_pm2_deployment()

def targetEnv  = (params.ENVIRONMENT ?: 'TEST').toUpperCase()
def currentEnv = inventory.cd('HRC-Kollect-BE', targetEnv)

node('HRC-Kollect-Jenkins-Agent') {
    cdpipeline.call([
        enable_jenkins_build_param_override: true,

        // WORKSPACE MANAGEMENT
        clean_workspace                 : true,

        // ARTIFACT CONFIGURATION (S3)
        artifact_s3_bucket_name         : 'hrc-cicd-test-bucket',
        artifact_s3_bucket_aws_region   : 'us-east-1',
        artifact_s3_keypath_destination : 'HRC-Kollect-BE',
        artifact_name                   : params.artifact_name ?: '',
        jenkins_aws_credentials_id      : 'hrc-aws-ecr-credentials',

        // TARGET VM & ENVIRONMENT BINDINGS
        server_ip                       : currentEnv.server_ip,
        deploy_dir                      : currentEnv.deploy_dir,
        app_name                        : currentEnv.app_name,
        node_version                    : 'v20.18.0',
        ssh_credentials_id              : currentEnv.ssh_creds,
        secret_arn                      : currentEnv.secret_arn,
        secret_region                   : 'us-east-1',
        run_db_migration                : false,
        start_command                   : 'yarn start',
        health_check_endpoint           : 'http://127.0.0.1:80/api/health',

        // NOTIFICATIONS
        notification_enabled                    : true,
        notification_channel                    : 'gmail',
        gmail_notification_from_email_id        : 'smtp@kernernorland.com',
        gmail_notification_recipients_email_ids : 'asangai@healthreconconnect.com'
    ])
}