@Library('jenkins-shared-libraries@feature-cicd') _
def cdpipeline = new opstree.cd.templates.ssh_pm2.ssh_pm2_deployment()

def artifactName = (env.artifact_name ?: params.artifact_name ?: env.image_tag ?: params.image_tag ?: '').trim()
def targetEnv    = (env.ENVIRONMENT ?: params.ENVIRONMENT ?: 'TEST').trim().toUpperCase()
def currentEnv   = inventory.cd('HRC-Kollect-Pay-Portal-Backend', targetEnv)

node('HRC-Kollect-Jenkins-Agent') {
    cdpipeline.call([
        enable_jenkins_build_param_override: true,

        // WORKSPACE MANAGEMENT
        clean_workspace                 : true,

        // ENVIRONMENT & BRANCH
        ENVIRONMENT                     : targetEnv,
        BRANCH                          : params.BRANCH ?: 'main',

        // ARTIFACT CONFIGURATION (S3)
        artifact_s3_bucket_name         : 'hrc-cicd-test-bucket',
        artifact_s3_bucket_aws_region   : 'us-east-1',
        artifact_s3_keypath_destination : 'HRC-Kollect-Pay-Portal-Backend',
        artifact_name                   : artifactName,

        // TARGET VM
        server_ip                       : currentEnv.server_ip,
        deploy_dir                      : currentEnv.deploy_dir,
        app_name                        : currentEnv.app_name,
        node_version                    : 'v20.18.0',
        ssh_credentials_id              : currentEnv.ssh_creds,
        secret_arn                      : currentEnv.secret_arn,
        secret_region                   : 'us-east-1',

        // RESOLVES PATH ALIASES (like 'middleware/jwt') IN NODE
        extra_env_vars                  : [
            'NODE_PATH': 'dist',
            'PORT'     : '3000',
            'NODE_ENV' : 'production'
        ],

        // STARTUP & HEALTH CHECK (PORT 3000)
        start_command                   : 'dist/server.js',
        health_check_endpoint           : 'http://127.0.0.1:3000/',

        // NOTIFICATIONS
        notification_enabled                    : true,
        notification_channel                    : 'gmail',
        gmail_notification_from_email_id        : 'smtp@kernernorland.com',
        gmail_notification_recipients_email_ids : 'asangai@healthreconconnect.com'
    ])
}