// @Library('jenkins-shared-libraries@feature-cicd') _

// def targetEnv = (params.ENVIRONMENT ?: 'DEV').toUpperCase()
// def imageTag = params.image_tag ?: 'latest'

// def envMap = [
//     'DEV' : [server_ip: '10.2.40.133', ecr_url: '167121004129.dkr.ecr.us-east-1.amazonaws.com/amd-sync-service-dev'],
//     'QA'  : [server_ip: '10.2.10.111', ecr_url: '167121004129.dkr.ecr.us-east-1.amazonaws.com/amd-sync-service-qa'],
//     'DEMO': [server_ip: '10.2.40.238', ecr_url: '167121004129.dkr.ecr.us-east-1.amazonaws.com/amd-sync-service-demo'],
//     'STG' : [server_ip: '10.2.40.170', ecr_url: '167121004129.dkr.ecr.us-east-1.amazonaws.com/amd-sync-service-stg'],
//     'PROD': [server_ip: '10.2.10.118', ecr_url: '167121004129.dkr.ecr.us-east-1.amazonaws.com/amd-sync-service-prod']
// ]

// def currentEnv = envMap[targetEnv] ?: envMap['DEV']

// node('HRC-Kollect-Jenkins-Agent') {
//     currentBuild.description = "CD: HRC-AMD-Sync-Service | Env: ${targetEnv} | Tag: ${imageTag}"

//     def cdPipeline = new opstree.cd.templates.docker_ecr.docker_ecr_deployment()
//     cdPipeline.call([
//         enable_jenkins_build_param_override: true,
//         image_name                          : 'hrc-amd-sync-service',
//         ecr_image_url                       : currentEnv.ecr_url,
//         server_ip                          : currentEnv.server_ip,
//         container_port                      : 8081,
//         notification_enabled               : true,
//         notification_channel               : 'gmail',
//         gmail_notification_from_email_id   : 'smtp@kernernorland.com',
//         gmail_notification_recipients_email_ids : 'asangai@healthreconconnect.com'
//     ])
// }
//-------------

@Library('jenkins-shared-libraries@feature-cicd') _

def targetEnv = (params.ENVIRONMENT ?: 'DEV').toUpperCase()
def imageTag = params.image_tag ?: 'latest'

def envMap = [
    'DEV' : [server_ip: '10.2.40.133', ssh_creds : 'HRC-Kollect-Dev-Server', app_name : 'hrc-amd-sync-service-dev'],
    'QA'  : [server_ip: '10.2.10.111', ssh_creds : 'HRC-Kollect-QA-Server', app_name : 'hrc-amd-sync-service-qa'],
    'DEMO': [server_ip: '10.2.40.238', ssh_creds : 'HRC-Kollect-Demo-Server', app_name : 'hrc-amd-sync-service-demo'],
    'STG' : [server_ip: '10.2.40.170', ssh_creds : 'HRC-Kollect-Stg-Server', app_name : 'hrc-amd-sync-service-stg'],
    'PROD': [server_ip: '10.2.10.118', ssh_creds : 'HRC-Kollect-PROD-Server', app_name : 'hrc-amd-sync-service-prod'],
    'TEST': [server_ip: '10.2.30.254', ssh_creds : 'HRC-Kollect-Test-Server', app_name : 'hrc-amd-sync-service-test']
]

def currentEnv = envMap[targetEnv] ?: envMap['DEV']

node('HRC-Kollect-Jenkins-Agent') {
    currentBuild.description = "CD: HRC-AMD-Sync-Service | Env: ${targetEnv} | Tag: ${imageTag}"

    def cdPipeline = new opstree.cd.templates.docker_ecr.docker_deployment()
    cdPipeline.call([
        enable_jenkins_build_param_override: true,

        // WORKSPACE MANAGEMENT
        clean_workspace                     : true,

        // APPLICATION / CONTAINER NAME
        app_name                            : currentEnv.app_name,
        
        // TARGET SERVER
        server_ip                           : currentEnv.server_ip,
        ssh_credentials_id                  : currentEnv.ssh_creds,

        // ECR
        ecr_account                         : '167121004129',
        ecr_region                          : 'us-east-1',
        ecr_repo                            : 'hrc-kollect-cicd/apps',

        // PORTS
        container_port                      : 8180,
        host_port                           : 8080,

        // NOTIFICATIONS
        notification_enabled                    : true,
        notification_channel                    : 'gmail',
        gmail_notification_from_email_id        : 'smtp@kernernorland.com',
        gmail_notification_recipients_email_ids : 'asangai@healthreconconnect.com'

        ])
}

