@Library('jenkins-shared-libraries@feature-cicd') _
def cipipeline = new opstree.ci.templates.java_ci.java_ci()

def targetEnv  = (params.ENVIRONMENT ?: 'TEST').toUpperCase()
def currentEnv = inventory.ci('HRC-AMD-Sync-Service', targetEnv)

node('HRC-Kollect-Jenkins-Agent') {
    cipipeline.call([
        enable_jenkins_build_param_override: true,

        // WORKSPACE MANAGEMENT
        clean_workspace                  : true,

        // VCS MANAGEMENT
        repo_https_url                   : 'https://gitlab.healthreconconnect.com/hrc/amd-sync-service.git',
        repo_ssh_url                     : 'git@gitlab.healthreconconnect.com:hrc/amd-sync-service.git',
        repo_branch                      : params.BRANCH ?: 'main',
        repo_url_type                    : 'http',
        jenkins_git_creds_id             : 'piyushu-gitlab-token',
        source_code_path                 : '',

        // PRE-BUILD CHECKS
        // CREDS SCANNING (GITLEAKS)
        gitleaks_check                   : true,
        fail_job_if_leak_detected        : false,
        gitleaks_scan_mode               : 'full',
        gitleaks_report_jenkins_publish  : true,

        // DEPENDENCY SCANNING (OWASP)
        dependency_check                          : 'true',
        dependency_scan_tool                      : 'owasp',
        owasp_project_name                        : 'hrc-amd-sync-service',
        owasp_report_publish                      : 'true',
        owasp_report_format                       : 'html',
        fail_job_if_dependency_returned_exception : 'false',
        nvd_api_key_creds_id                      : 'NVD_API_KEY',

        // BUILD & PACKAGE ARTIFACT (JAVA / MAVEN)
        perform_code_build               : true,
        build_tool                       : 'maven',
        app_name                         : 'hrc-amd-sync-service',
        withmaven_globaltool_jdk         : 'Java 17',
        withmaven_globaltool_maven       : 'Maven 3.9',

        // UNIT TEST & CODE COVERAGE
        unit_testing_check               : 'true',
        fail_job_if_unit_issue_detected  : 'false',
        unit_test_reports_path           : '**/target/surefire-reports/*.xml',

        // STATIC CODE ANALYSIS (SONARQUBE)
        static_code_analysis_check              : true,
        codebase_to_scan_directory              : '.',
        sonar_project_key                       : 'hrc-amd-sync-service',
        sonar_project_name                      : 'hrc-amd-sync-service',
        sonar_sources                           : 'src/main/java',
        sonar_extra_args                        : '',
        fail_job_if_analysis_returned_exception : 'false',
        jenkins_sonarqube_token_creds_id        : 'HRC_SONARQUBE_TOKEN',

        // PUBLISH TO S3
        artifact_publish_check           : true,
        artifact_destination_type        : 'S3',
        jenkins_aws_credentials_id       : currentEnv.credentials_id,
        artifact_s3_bucket_aws_region    : currentEnv.aws_region,
        artifact_s3_bucket_name          : currentEnv.artifact_s3_bucket_name,
        artifact_s3_keypath_destination  : currentEnv.artifact_s3_keypath,

        // TRIGGER CD PIPELINE (Recreate Mode)
        enable_trigger_cd_pipeline       : params.TRIGGER_CD != null ? params.TRIGGER_CD : true,
        trigger_cd_pipeline_path         : 'Healthcare/CD/HRC-AMD-Sync-Service',
        image_tag_build_param            : 'artifact_name',
        environment                      : targetEnv,

        // NOTIFICATION
        notification_enabled                    : true,
        notification_channel                    : 'gmail',
        gmail_notification_from_email_id        : 'smtp@kernernorland.com',
        gmail_notification_recipients_email_ids : 'asangai@healthreconconnect.com'
    ])
}
